services:
  web:
    build: .
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file: .env
    depends_on:
      elasticsearch:
        condition: service_healthy
    command: >
      sh -c "
      python search_service/create_index.py &&
      uvicorn src.api:app --host 0.0.0.0 --port 8000 --reload
      "

  elasticsearch:
    image: elasticsearch:7.17.23
    ports:
      - 9200:9200
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:9200/_cluster/health?wait_for_status=yellow&timeout=5s || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 3
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false

  kibana:
    container_name: kibana
    image: kibana:7.17.23
    restart: always
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200 
    ports:
      - 5601:5601
    depends_on:
      elasticsearch:
        condition: service_healthy
