name: FAQ Genius CI

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  backend-build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Start containers
        run: 	docker compose up --build -d --remove-orphans

      - name: Stop containers
        if: always()
        run: docker compose down
